# Generated by Django 6.0.2 on 2026-03-14 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Updated'), ('file_view', 'Viewed File'), ('file_upload', 'Uploaded File'), ('file_checkout', 'Checked Out File'), ('file_checkin', 'Returned File'), ('file_request', 'Requested File'), ('request_approve', 'Approved Request'), ('request_reject', 'Rejected Request'), ('request_handover', 'Handed Over File'), ('user_create', 'Created User'), ('user_update', 'Updated User'), ('department_create', 'Created Department'), ('department_update', 'Updated Department')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='register_ac_user_id_6de5ea_idx'), models.Index(fields=['action', '-timestamp'], name='register_ac_action_fe1c80_idx')],
            },
        ),
    ]
