# Generated by Django 6.0.2 on 2026-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_filetag_file_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Main document file', null=True, upload_to='files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='file',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='changes_summary',
            field=models.TextField(blank=True, help_text='Summary of changes from previous version'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='file_versions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
