# Generated by Django 6.0.2 on 2026-03-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_file_file_attachment_file_original_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('missing_pages', 'Missing Pages'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='return_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='return_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filerequest',
            name='return_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ready_for_pickup', 'Ready for Pickup'), ('handed_over', 'Handed Over'), ('pending_return', 'Pending Return Confirmation'), ('returned_verified', 'Returned & Verified'), ('return_rejected', 'Return Rejected'), ('confirmed', 'Confirmed by User'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
