# Generated by Django 6.0.2 on 2026-03-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_filerequest_return_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='approved_version',
            field=models.ForeignKey(blank=True, help_text='The file version that was approved and handed over to the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='register.fileversion'),
        ),
    ]
