# Generated by Django 6.0.2 on 2026-04-04 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_filerequest_approved_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status', 'department'], name='register_fi_status_9201ef_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['current_holder', 'status'], name='register_fi_current_bbd175_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at', 'status'], name='register_fi_created_be26ff_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['year', 'department'], name='register_fi_year_08fb28_idx'),
        ),
        migrations.AddIndex(
            model_name='filerequest',
            index=models.Index(fields=['status', 'created_at'], name='register_fi_status_92bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='filerequest',
            index=models.Index(fields=['requesting_user', 'status'], name='register_fi_request_980173_idx'),
        ),
        migrations.AddIndex(
            model_name='filerequest',
            index=models.Index(fields=['file', 'status'], name='register_fi_file_id_346acf_idx'),
        ),
        migrations.AddIndex(
            model_name='filerequest',
            index=models.Index(fields=['status', 'processed_by'], name='register_fi_status_b84952_idx'),
        ),
    ]
