# Generated by Django 6.0.2 on 2026-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_add_file_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Marked as archived for retention policy'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Updated'), ('file_view', 'Viewed File'), ('file_download', 'Downloaded File'), ('file_upload', 'Uploaded File'), ('file_checkout', 'Checked Out File'), ('file_checkin', 'Returned File'), ('file_request', 'Requested File'), ('request_approve', 'Approved Request'), ('request_reject', 'Rejected Request'), ('request_handover', 'Handed Over File'), ('user_create', 'Created User'), ('user_update', 'Updated User'), ('department_create', 'Created Department'), ('department_update', 'Updated Department'), ('comment_added', 'Added Comment'), ('file_return_verified', 'Return Verified'), ('file_return_rejected', 'Return Rejected')], max_length=30),
        ),
    ]
