# Generated by Django 6.0.2 on 2026-04-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_add_api_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_request_approved', models.BooleanField(default=True)),
                ('email_request_rejected', models.BooleanField(default=True)),
                ('email_file_due', models.BooleanField(default=True)),
                ('email_file_overdue', models.BooleanField(default=True)),
                ('email_return_verified', models.BooleanField(default=True)),
                ('email_return_rejected', models.BooleanField(default=True)),
                ('email_new_request', models.BooleanField(default=True)),
                ('email_weekly_summary', models.BooleanField(default=False)),
                ('in_app_notifications', models.CharField(choices=[('all', 'All'), ('important', 'Important Only'), ('none', 'None')], default='all', max_length=20)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
