# Generated by Django 6.0.2 on 2026-04-11 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_accesslog_loginattempt_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecomment',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'File comments'},
        ),
        migrations.AddField(
            model_name='filecomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='register.filecomment'),
        ),
    ]
