# Generated by Django 6.0.2 on 2026-04-18 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_filecomment_options_filecomment_is_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lifecycle_state',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('approved', 'Approved'), ('checked_out', 'Checked Out'), ('returned', 'Returned'), ('archived', 'Archived')], default='available', help_text='Formalized lifecycle state for transition validation', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='lifecycle_transition_at',
            field=models.DateTimeField(blank=True, help_text='When the state last changed', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lifecycle_transition_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered the last state change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
