# Generated by Django 6.0.2 on 2026-04-18 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_add_task_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_audit_trail', 'Can view audit trail'), ('export_audit_trail', 'Can export audit trail')], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='checksum',
            field=models.CharField(blank=True, help_text='Checksum for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entry_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of this entry', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_hash',
            field=models.CharField(blank=True, help_text='Hash of previous entry for chaining', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subsystem',
            field=models.CharField(default='main', help_text='System subsystem that generated this log', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Updated'), ('file_view', 'Viewed File'), ('file_download', 'Downloaded File'), ('file_upload', 'Uploaded File'), ('file_checkout', 'Checked Out File'), ('file_checkin', 'Returned File'), ('file_request', 'Requested File'), ('request_approve', 'Approved Request'), ('request_reject', 'Rejected Request'), ('request_handover', 'Handed Over File'), ('user_create', 'Created User'), ('user_update', 'Updated User'), ('department_create', 'Created Department'), ('department_update', 'Updated Department'), ('comment_added', 'Added Comment'), ('file_return_verified', 'Return Verified'), ('file_return_rejected', 'Return Rejected'), ('file_state_change', 'File State Changed'), ('request_state_change', 'Request State Changed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp', 'subsystem'], name='register_ac_timesta_9b016c_idx'),
        ),
    ]
