# Generated by Django 6.0.2 on 2026-04-19 07:07

import django.db.models.deletion
import django.utils.timezone
import register.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_audit_trail_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='signature',
            field=models.TextField(blank=True, help_text='Digital signature for approvals'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='signature_algorithm',
            field=models.CharField(blank=True, help_text='Signature algorithm used', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='signature_verified',
            field=models.BooleanField(default=False, help_text='Whether signature has been verified'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='User who digitally signed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(help_text='PEM-encoded public key')),
                ('private_key_encrypted', models.TextField(help_text='Encrypted PEM-encoded private key')),
                ('key_fingerprint', models.CharField(help_text='SHA-256 fingerprint of public key', max_length=64, unique=True)),
                ('certificate_serial', models.CharField(help_text='Certificate serial number', max_length=64, unique=True)),
                ('certificate_not_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_not_after', models.DateTimeField(default=register.models.get_default_expiry)),
                ('salt', models.CharField(help_text='Salt for key derivation', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
